name: Playwright .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # ili 7.0.x, u zavisnosti od tvoje verzije

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install Playwright browsers
        run: pwsh ./bin/Debug/net8.0/playwright.ps1 install

      - name: Run Playwright tests
        run: dotnet test --filter TestCategory=Playwright
